apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: coinflip
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: benmoss/coinflip:latest
          env:
            - name: OTLP_TRACE_ENDPOINT
              value: otel-collector.observability:4317
